---
global:
  pattern: multicloud-gitops

  options:
    useCSV: false
    syncPolicy: Automatic
    installPlanApproval: Automatic

main:
  clusterGroupName: hub

quay:
  username: quayadmin
  password: quayadmin123
  email: gmidha@redhat.com
